// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoD4TcKB6ob0a0FkX95sJ6l3GqMxHGEnw',
    appId: '1:862493235616:web:3fab8bb8908cd9fd622cc5',
    messagingSenderId: '862493235616',
    projectId: 'dillydaily-13234',
    authDomain: 'dillydaily-13234.firebaseapp.com',
    storageBucket: 'dillydaily-13234.firebasestorage.app',
    measurementId: 'G-MYYFHRMZM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMMjpV4028O5B9Up2PBlSE3aiKLb5OLC8',
    appId: '1:862493235616:android:41479c3fa3e3bbc6622cc5',
    messagingSenderId: '862493235616',
    projectId: 'dillydaily-13234',
    storageBucket: 'dillydaily-13234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7wdQtR6E3MSlv3zxdArPDloT0hseUOw',
    appId: '1:862493235616:ios:380762bd90111f7c622cc5',
    messagingSenderId: '862493235616',
    projectId: 'dillydaily-13234',
    storageBucket: 'dillydaily-13234.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU7wdQtR6E3MSlv3zxdArPDloT0hseUOw',
    appId: '1:862493235616:ios:380762bd90111f7c622cc5',
    messagingSenderId: '862493235616',
    projectId: 'dillydaily-13234',
    storageBucket: 'dillydaily-13234.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoD4TcKB6ob0a0FkX95sJ6l3GqMxHGEnw',
    appId: '1:862493235616:web:3a80938ad6a1f50b622cc5',
    messagingSenderId: '862493235616',
    projectId: 'dillydaily-13234',
    authDomain: 'dillydaily-13234.firebaseapp.com',
    storageBucket: 'dillydaily-13234.firebasestorage.app',
    measurementId: 'G-M0HEDD1G4K',
  );
}
